apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-deployment
      labels:
        app: api
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: api
      template:
        metadata:
          labels:
            app: api
            gitcommit: ${CICD_GIT_COMMIT}
        spec:
          containers:
            - name: api
              image: ederpfonseca/nginx
              ports:
                - containerPort: 8000

  - apiVersion: v1
    kind: Service
    metadata:
      name: api-service
    spec:
      selector:
        app: api
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
